name: Airline Change
description: Request an airline data change
labels: ["airline", "pending triage"]
assignees: ["daniluk4000"]
body:
  - type: markdown
    attributes:
      value: |
        Hello! Thank you for reporting an issue in VATSIM Radar Data.
        
        Before reporting, please also check existing issues in this repository - you can filter them by "airline" label (also check closed ones).

        Trying to make VA to show on VR via remarks? Add it to custom-data, or to https://gng.aero-nav.com/AERONAV/icao_fhairlines
  - type: input
    id: id
    attributes:
      label: Your Vatsim CID
      description: It is your Vatsim login. Required for us to contact you in Discord if you're there.
    validations:
      required: true
  - type: dropdown
    id: proposing
    attributes:
      label: What do you propose?
      options:
        - New airline(s) (for example, VA)
        - Changes to existing airline(s)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Airline(s) ICAO
      description: Please include your Airline(s) ICAO
      placeholder: SBI, AFL
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: Describe proposed change
      description: "Include what needs to be changed or added: name, or callsign"
      placeholder: "ICAO: SBI, Name: S7 Airlines, Callsign: Siberian"
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Why do you need that?
      description: "Example: you are VA owner, matches real world change (include source), etc"
    validations:
      required: true
  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      options:
        - label: I have searched for other issues and didn't found any alike
          required: true
